Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,16 @@ jobs:
         WRAPPED_FILE=$(mktemp)
         jq -n --argjson collection "$(cat "$COLLECTION_FILE")" '{collection: $collection}' > "$WRAPPED_FILE"
 
-        curl --location --request POST "https://api.getpostman.com/collections" \
+       response=$(curl --location --request POST "https://api.getpostman.com/collections" \
         --header "X-Api-Key: $POSTMAN_API_KEY" \
         --header "Content-Type: application/json" \
-        --data @"$WRAPPED_FILE"
+        --data @"$WRAPPED_FILE")
+          COLLECTION_ID=$(echo "$response" | jq -r '.collection.id')
+
+          if [ -z "$COLLECTION_ID" ] || [ "$COLLECTION_ID" == "null" ]; then
+            echo "Failed to import collection. Response: $response"
+            exit 1
+          fi
+
+          echo "Imported collection: $COLLECTION_NAME with ID $COLLECTION_ID"
+          echo "COLLECTION_ID=$COLLECTION_ID" >> $GITHUB_ENV
